language: go

git:
  submodules: false

before_install:
- sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- openssl aes-256-cbc -K $encrypted_dd8e37a50f09_key -iv $encrypted_dd8e37a50f09_iv
  -in travis_blog_rsa.enc -out travis_blog_rsa -d

install:
- mv t2/file4.txt file4.txt
#- go get github.com/spf13/hugo
- cat file4.txt

script:
- mv file4.txt t2/file4.txt
- cat t2/file4.txt
- echo "travis commit message:" $TRAVIS_COMMIT_MESSAGE >> t2/file4.txt
- cat t2/file4.txt
#- pwd
- ls -l
